apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog-apps
  namespace: argocd
spec:
  generators:
    git:
      repoURL: https://github.com/0xMordecai/blog-environments.git
      revision: dev
      directories:
      - path: Manifests/*
      - path: Manifests/argoCD
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xMordecai/blog-environments.git
        targetRevision: dev
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true