apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-components
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/0xMordecai/blog-environments.git
    targetRevision: dev
    path: Manifest/Monitoring/Prometheus/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
        automated:
          selfHeal: true  