---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCKh7pdiznlKd4bbykBKnFWs/UyF2qv7Ag0bxtIuQdJJsimI7daoLWR/XE68zgUTABO47o4oznXp3Rh9KTEHiLDIc/gZrRBPslEiM26Bo+z+NRvhXsHBNEmgfMaIJz4m+TveCcOtcQ/Xr5iaZYR1WzDB+Ajx8DmCPRz0mthTfoAwlk8NqKQIueIx4eK7l0kBr0BpVQAGDc35OMxg3KQC/n9yV7MUXogrrUZfo48Pha1XEptJFzUvr4/yp+w85i8Q1i46f03Xxf9ECgi8A5MGDb61n/vE+yity7hh+igl+HNaURkofMIotcKMraHJU1OL0uGgBmmJ5VyXwlFryn0TkTeaHU51Xl04I8M8G9bCoYRJoLukiImaWM0EOU4Rziu8ui+0NGN+kDEOPG0UqEho6ObylaxGBzHr8BnFz/4Ffbq0t3l4ebRe922OH9reNjgGeTTpTwpZVMALc4xjMibDzMmPeofbZP3FEcHk7ZE0tZGh2D/p33jxGiFyHZrAfEH8BCYfnyK0VVNSg7dYb6O7xvlBcxjywpFIaGMIoXCKiznqTlMCdvH3igp/7uB6ASocVnmq0x8EqwZ8+Mk9DVpTgIzfUaT1IgydgXvm5jqTvHCQgCBkwNFuZN92T68FVFtMPwbR5nQ7J2KmSlQMxTi8dA6L4tFFR87IJ8+ISbda3qmBh3h5B1qZmguHWZqZ9nuOAW6y0nk
    MONGO_INITDB_ROOT_USERNAME: AgBi6U64joq68kRGhn3SEpGQEtxKEsI/o+mSr/EszkyED9XjfP1uGP+V3lXlb8vkPBblZLlShJ/9xbUZgStPlUJnUJeTyKmODW8SoeEtljOKA7G7UUnFXMCpjgraZaEsExqfAXJGgqvtO6B34sRO7K9bpO2Rgb/oH36BNnlek0ODgJZPsdCLPYC+iurnBxhN7zW0yMhL0b+7Bvk7+/bvCY69OgSekwXQEJd5Vv7j0to3UU9aEg/F5OZnSLIaKwWOrTLSL8kQlW7XerMdStuN8xhCjQgQfbNgKchEgp/27+EeVVB5kS4rFXJV7pLVyaqPtL6Q3Vx3m2EAOV/8TZdeOCvKKAaDnJ//q0uD7kOOHEm8bmhcchbX6hpTlmD+4WmIO/2cd1zHwLvB+uR5b5iH3nlKO9pNDBAHvCfCnWRe0nYRZyw4dFOgh4WLr2es5NDXcV+7B6RV5N5Smkle6LdyHnfOEmaxsD7wTRAFQCv9mWV4DJUzfuPQRpVsYIdtkZLIDqHKJVk+Attv3IEPb6Y0zr/0WsKDW81AmsTNJV6x+GfxPOfkPSuaLK3/fBc/Vo+JxmJhnlFcrULAe+jdmOqH4Ex69I2NlrWuqyE/n20FDJZJ6QjUAlvGxN5UusvP+HekvDMfdaYxFk47zz9RNhswt1SpwCe7+4+vVze0+C3KXcLb0+SPCDbwikBQfrTmTCsTJu6U2lAE
  template:
    metadata:
      name: mongodb-creds
      namespace: blog-app
